app:
  name: CurrencyExchangeApp
  port: :3000

database:
  dsn: "root:522ciyuan@tcp(127.0.0.1:3306)/currency_exchange_db?charset=utf8mb4&parseTime=True&loc=Local"
  MaxIdleConns: 11
  MaxOpenConns: 114
  